language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc

branches:
  only:
    - master-dry
    - develop-dry

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-rosdep -qq
  - sudo rosdep init
  - rosdep update 
  - mkdir -p /tmp/ws/
  - ln -s `pwd` /tmp/ws/
  - cd /tmp/ws
  - rosdep install --from-paths src --ignore-src --rosdistro fuerte -y

script:
  - source /opt/ros/fuerte/setup.bash
  - rosmake
